apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nacos-1-4-1
  name: nacos-1-4-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nacos-1-4-1
  template:
    metadata:
      labels:
        name: nacos-1-4-1
    spec:
      containers:
      - env:
        - name: PREFER_HOST_MODE
          value: hostname
        - name: MODE
          value: standalone
        - name: SPRING_DATASOURCE_PLATFORM
          value: mysql
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_SERVICE_DB_NAME
          value: nacos
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_USER
          value: nacos
        - name: MYSQL_SERVICE_PASSWORD
          value: nacos
        - name: MYSQL_SERVICE_DB_PARAM
          value: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
        image: nacos/nacos-server:1.4.1
        imagePullPolicy: IfNotPresent
        name: nacos-1-4-1
        ports:
        - containerPort: 8848
          name: 8848tcp
          protocol: TCP
        - containerPort: 7848
          name: 7848tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-1-4-1
  labels:
    name: nacos-1-4-1
spec:
  type: NodePort
  ports:
  - port: 8848
    targetPort: 8848
    protocol: TCP
    nodePort: 30001
  selector:
    name: nacos-1-4-1